---
title: "Palmer Penguins for R"
author: "Riya Mathew Kovoor"
date: 2026-09-23
---
Analysis for R

## Data

Data: [Palmer Penguins](https://allisonhorst.github.io/palmerpenguins/), Palmer Station Antarctica LTER.

## Installation of Libraries
```{r}
#| message: false
#| warning: false
library(palmerpenguins)
library(tidyverse)
```

## Exploring the Data

```{r}
penguins_data <- penguins
head(penguins_data)

#| label: fig-penguin-mass
#| fig-cap: "Body mass of penguins by species."
```

## Data Wrangling

#### **Let's remove all the empty NA values.**
```{r}
penguins_data <- penguins_data |>
    drop_na()
head(penguins_data)
```

#### **Why don't we sort the rows based on decreasing value of body mass?**

```{r}
penguins_data <- penguins_data |>
    arrange(desc(body_mass_g))

head(penguins_data)
```

#### **How does average body mass differ between species?**

```{r}
penguins_data <- penguins_data |>
    group_by(species) |>
    summarise(mean_body_mass = mean(body_mass_g))
penguins_data
```